security:
    encoders:
        BackOfficeBundle\Entity\User:
            algorithm: bcrypt
            cost: 12
    providers:
        database_users:
            entity: { class: BackOfficeBundle:User, property: username }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            guard:
                authenticators:
                    - back_office.form_login_authenticator
            logout:
                path: /auth/logout
                target: /auth/login
    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/auth/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/backoffice/, roles: ROLE_ADMIN }

