# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
     middleware.form_login_authenticator:
         class: MiddlewareBundle\Security\FormLoginAuthenticator
         arguments: ["@router", "@security.password_encoder", "@form.factory"]