services:
    acme.doctrine.dbal.events.oracle_session_init.listener:
        class: %doctrine.dbal.events.oracle_session_init.class%
        tags:
            - { name: doctrine.event_listener, event: postConnect }
    acme.doctrine.dbal.oracle_platform.type_mapping.listener:
        class: MiddlewareBundle\Listener\OracleDoctrineTypeMappingListener
        tags:
            - { name: doctrine.event_listener, event: postConnect }