services:
    doctrine.dbal.events.oracle_session_init.listener:
        class: Doctrine\DBAL\Event\Listeners\OracleSessionInit
        tags:
            - { name: doctrine.event_listener, event: postConnect }
    doctrine.dbal.oracle_platform.type_mapping.listener:
        class: MiddlewareBundle\Listener\OracleDoctrineTypeMappingListener
        tags:
            - { name: doctrine.event_listener, event: postConnect }