# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
     back_office.form_login_authenticator:
         class: BackOfficeBundle\Security\FormLoginAuthenticator
         arguments: ["@router", "@security.password_encoder", "@form.factory"]
     user.type:
         class: BackOfficeBundle\Form\UserType
         calls:
             - [ setContainer, [ "@service_container" ] ]