<?php

namespace FrontBundle;

use Symfony\Component\HttpKernel\Bundle\Bundle;

class FrontBundle extends Bundle
{
    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }
}
